source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ADGContainerKit_Example', :exclusive => true do
  pod "ADGContainerKit", :path => "../"
end

target 'ADGContainerKit_Tests', :exclusive => true do
  pod "ADGContainerKit", :path => "../"

  
end
